version: "2.4"

services:
  strfry-relay:
    container_name: strfry-relay
    image: dockurr/strfry:latest
    mem_limit: 1024m
    cpus: 0.2
    environment:
      VIRTUAL_HOST: relay.angor.io
      VIRTUAL_PORT: 7777
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: relay.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
    restart: unless-stopped
    volumes:
      - ./strfry/:/app/strfry-db
      - ./strfry/strfry.conf:/etc/strfry.conf
    networks:
      - proxy

  web:
    image: getumbrel/umbrel-nostr-relay
    user: "1000:1000"
    container_name: public-relay-web
    restart: on-failure
    environment:
      RELAY_HOST: "strfry-relay"
      RELAY_PORT: "7777"
    ports:
      - 3000:3000
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy