version: "2.4"

services:
  strfry-relay:
    container_name: strfry-relay
    image: dockurr/strfry:latest
    mem_limit: 1024m
    cpus: 0.2
    restart: unless-stopped
    volumes:
      - ./strfry/:/app/strfry-db
      - ./strfry/strfry.conf:/etc/strfry.conf
    ports:
      - "0.0.0.0:7777:7777"
    expose:
      - 7777
    networks:
      - nostr-network

  web:
    image: getumbrel/umbrel-nostr-relay
    user: "1000:1000"
    container_name: public-relay-web
    restart: on-failure
    environment:
      RELAY_HOST: "strfry-relay"
      RELAY_PORT: "7777"
    ports:
      - "0.0.0.0:3000:3000"
    expose:
      - 3000
    networks:
      - nostr-network

  caddy:
    container_name: caddy
    image: caddy:2.8
    mem_limit: 256m
    cpus: 0.1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=debugrelay.angor.online
      - EMAIL=admin@blockcore.net
    networks:
      - nostr-network

networks:
  nostr-network:
    name: nostr-network

volumes:
  caddy_data:
  caddy_config: